export const brand = {
  name: "AZIL HEALTHCARE",
  phone: "9786994312",
  alternatePhone: "9840616437",
  email: "azilhealthcare@gmail.com",
  address: "No.14, Old Thirukolakudi, Thirupathur, Sivaganga, Tamil Nadu - 630405",
  hours: "Monday - Saturday, 9:00 AM - 6:00 PM (Sunday Holiday)",
};

export const productCategories = [
  {
    title: "Operation Theatre Equipment",
    imageKey: "ot",
    items: [
      "OT Lights",
      "OT Tables",
      "Anesthesia Workstations",
      "Electrosurgical Units (ESU)",
      "Suction Units",
      "Tourniquet Systems",
      "OT Accessories",
    ],
    icon: "✚",
  },
  {
    title: "ICU & Critical Care Equipment",
    imageKey: "icu",
    items: [
      "Ventilators",
      "Patient Monitors",
      "Infusion Pumps",
      "Syringe Pumps",
      "Defibrillators",
      "BIPAP / CPAP",
      "High Flow Oxygen Therapy",
      "ICU Accessories",
    ],
    icon: "♡",
  },
  {
    title: "Endoscopy Equipment",
    imageKey: "endoscopy",
    items: [
      "Rigid Bronchoscopy Sets",
      "Rigid Thoracoscopy Sets",
      "Laparoscopy Sets",
      "Endoscopy Camera Systems",
      "Video Processors",
      "Light Sources",
      "Endoscopy Accessories",
    ],
    icon: "◎",
  },
  {
    title: "Patient Monitoring Equipment",
    imageKey: "monitoring",
    items: [
      "Multipara Monitors",
      "ECG Machines",
      "Pulse Oximeters",
      "NIBP Monitors",
      "Fetal Monitors",
      "Capnography (EtCO₂)",
      "Central Monitoring Systems",
      "Monitoring Accessories",
    ],
    icon: "▣",
  },
  {
    title: "Hospital Furniture",
    imageKey: "furniture",
    items: [
      "Hospital Beds (Manual / Electric)",
      "ICU Beds",
      "Bedside Trolleys",
      "Crash Carts",
      "Stainless Steel Furniture",
      "Over Bed Tables",
      "Ward Furniture & Accessories",
    ],
    icon: "⌑",
  },
  {
    title: "Medical Consumables",
    imageKey: "consumables",
    items: [
      "BP Bladders & Cuffs",
      "Suction Catheters",
      "IV Sets",
      "Surgical Gloves",
      "Surgical Masks",
      "Wound Care Products",
      "Biomedical Waste Bins",
      "Other Hospital Consumables",
    ],
    icon: "✣",
  },
  {
    title: "Medical Gas & ICU Infrastructure",
    imageKey: "gas",
    items: [
      "Medical Gas Manifold Systems",
      "Bed Head Panels",
      "Oxygen Points",
      "Vacuum & Air Systems",
      "Pipeline Accessories",
      "Installation Support",
    ],
    icon: "♧",
  },
  {
    title: "Other Medical Equipment",
    imageKey: "other",
    items: [
      "Autoclaves",
      "Suction Units",
      "Nebulizers",
      "UV Sterilizers",
      "Examination Lights",
      "Weighing Scales",
      "Biomedical Waste Management",
      "Other Hospital Equipment",
    ],
    icon: "▤",
  },
] as const;

export const brandNames = [
  "ST SURGICALS",
  "mindray",
  "Dräger",
  "BPL",
  "PHILIPS",
  "STERIS",
  "GETINGE",
  "RICHARD WOLF",
  "OLYMPUS",
] as const;

export const services = [
  {
    title: "Installation & Commissioning",
    imageKey: "installation",
    text: "Professional installation and commissioning of medical equipment by trained engineers.",
  },
  {
    title: "Preventive Maintenance (AMC)",
    imageKey: "maintenance",
    text: "Regular maintenance to ensure reliable and uninterrupted performance of your equipment.",
  },
  {
    title: "Repair & Servicing",
    imageKey: "repair",
    text: "Quick and efficient repair services with genuine spares and professional support.",
  },
  {
    title: "Calibration & Testing",
    imageKey: "calibration",
    text: "Accurate calibration and performance testing as per manufacturer standards.",
  },
  {
    title: "Spare Parts Support",
    imageKey: "spareParts",
    text: "Supply of genuine and compatible spare parts for multiple brands.",
  },
  {
    title: "User Training",
    imageKey: "training",
    text: "On-site training for hospital staff to ensure safe and effective use of equipment.",
  },
] as const;
